apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: products
  namespace: tech-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70